language: rust

rust:
  - stable

jobs:
  include:
    - os: osx
      arch: amd64
      env: ENV_NAME="x86_64-apple-darwin"
    - os: windows
      arch: amd64
      env: ENV_NAME="x86_64-pc-windows-msvc"
    - os: linux
      arch: amd64
      env: ENV_NAME="x86_64-unknown-linux-gnu"
    - os: linux
      arch: arm64
      env: ENV_NAME="aarch64-unknown-linux-gnu"

install:
  - cd crates/cli
  - cargo build --release
  - cd ../..

script:
  - mkdir wasm-bindgen-$TRAVIS_TAG-$ENV_NAME
  - cp ./target/release/wasm-bindgen wasm-bindgen-$TRAVIS_TAG-$ENV_NAME
  - tar -czf wasm-bindgen-$TRAVIS_TAG-$ENV_NAME.tar.gz wasm-bindgen-$TRAVIS_TAG-$ENV_NAME

deploy:
  provider: releases
  overwrite: false
  token: $GITHUB_TOKEN
  skip_cleanup: true
  file: "wasm-bindgen-$TRAVIS_TAG-$ENV_NAME.tar.gz"
  name: Release $TRAVIS_TAG
  on:
    repo: second-state/wasm-bindgen
    tags: true
